### ISSUE TITLE
登录页的Set-cookie功能失效

### ISSUE THREAD

**Issue by lichaozhy** [iswangyj/cas-server-demo#1]
正常情况下登录页面会提供JSESSIONID，但现在只有默认的登出页面会Set-cookie，增加会话ID。
你现在做的实现不正常，你可以看看公司的sso的效果http://sso.or-change.cn/cas/login。这个请求就包含了创建会话。你的实现没有这部分

**Comment by iswangyj** [comment]
添加依赖cas-server-support-pac4j-webflow即可解决
https://apereo.github.io/cas/5.2.x/integration/Delegate-Authentication.html
